# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
CPU_NODE            = 1
MEMORY_NODE         = 1024
WORKER_NODES_COUNT  = 2


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "core" do |node|
  
    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.hostname          = "core.funless.dev"

    node.vm.network "private_network", ip: "192.168.56.100"
  
    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_NODE
      v.nested  = true
      v.cpus    = CPU_NODE
    end
  
    node.vm.provision "shell", path: "bootstrap_core.sh"
  
  end


  # Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "worker#{i}" do |node|

      node.vm.box               = VAGRANT_BOX
      node.vm.box_check_update  = false
      node.vm.hostname          = "worker#{i}.funless.dev"

      node.vm.network "private_network", ip: "192.168.56.10#{i}"

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_NODE
        v.nested  = true
        v.cpus    = CPU_NODE
      end

      node.vm.provision "shell", path: "bootstrap_worker.sh"

    end

  end

end
